name: java cd with gradle
on:
  workflow_run:
    workflows: [ "java ci with gradle" ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: download repo
        uses: actions/checkout@v4
      - name: set up jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a
      - name: make gradlew executable
        run: chmod +x ./gradlew
      - name: build with gradle wrapper
        run: ./gradlew build
      - name: configure aws credentials and region
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: 'us-east-1'
      - name: deploy to aws cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: 'holamundo-github--actions-test'
          template: './main.yml'
          no-fail-on-empty-changeset: "1"
      - name: last commit sha value
        run: echo "SHA=${{ github.sha }}" >> $GITHUB_ENV